ALTER TABLE department
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS monthly_budget NUMERIC(15, 2),
    ADD COLUMN IF NOT EXISTS location VARCHAR(200),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(30),
    ADD COLUMN IF NOT EXISTS fax VARCHAR(30),
    ADD COLUMN IF NOT EXISTS phone_extension VARCHAR(20),
    ADD COLUMN IF NOT EXISTS email VARCHAR(120),
    ADD COLUMN IF NOT EXISTS responsible_collaborator_ids JSONB NOT NULL DEFAULT '[]'::jsonb;
