package br.com.gommo.modules.rh.person.exitinterview.entity;

public enum ExitInterviewTerminationTypeEnum {
    CLT_RESIGNATION,
    CLT_DISMISSAL_WITHOUT_CAUSE,
    CLT_DISMISSAL_WITH_CAUSE,
    CLT_PROBATION_CONTRACT_END,
    CLT_FIXED_TERM_CONTRACT_END,
    CLT_MUTUAL_AGREEMENT,
    CLT_RETIREMENT,
    CLT_DEATH,
    CLT_OTHER,
    PJ_COMPANY_INITIATIVE,
    PJ_PROVIDER_INITIATIVE,
    PJ_CONTRACT_END,
    PJ_MUTUAL_AGREEMENT,
    PJ_CONTRACT_BREACH,
    PJ_PROVIDER_REPLACEMENT,
    PJ_OTHER
}